/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import agenda.Agenda;
import agenda.Contacto;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;

/**
 *
 * @author kanutto
 */
public class JframeInicio extends javax.swing.JFrame {

    /**
     * Creates new form JframeInicio
     */
    private String nombre=null;
    DefaultListModel<String> model = new DefaultListModel<>(); 
    
   private DefaultListModel modelList() throws FileNotFoundException {
       
      
        Agenda agen=new Agenda("C:\\Users\\kanutto\\Documents\\NetBeansProjects\\AGENDA\\Agenda.txt");
               
        
        for(Contacto c:agen.getListaContactos()){
           model.addElement(c.getNombre());
        }
        
     
        return model;
    }
   
   public String getNombre(){
       return nombre;
   }
   
    public JframeInicio() throws FileNotFoundException   {
        initComponents();
      
        jListContactos.setModel(modelList());
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListContactos = new javax.swing.JList<>();
        jButtonSelect = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonAñadir = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonExportar = new javax.swing.JButton();
        jButtonImportar = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setForeground(new java.awt.Color(204, 204, 255));

        jListContactos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jScrollPane1.setViewportView(jListContactos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 530, 240));

        jButtonSelect.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonSelect.setText("Select");
        jButtonSelect.setPreferredSize(new java.awt.Dimension(109, 37));
        jButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 440, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Contactos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        jButtonAñadir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonAñadir.setText("Añadir");
        getContentPane().add(jButtonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 300, 110, -1));

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setPreferredSize(new java.awt.Dimension(109, 37));
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 370, -1, -1));

        jButtonExportar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonExportar.setText("Exportar");
        getContentPane().add(jButtonExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, -1, -1));

        jButtonImportar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonImportar.setText("Importar");
        getContentPane().add(jButtonImportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 540, -1, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/62863877-red-white-wallpapers.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectActionPerformed
      int pos=jListContactos.getSelectedIndex();
      nombre=model.get(pos);
      System.out.println(nombre);
        try {
            JframeContacto nuevaVentana= new JframeContacto();
            nuevaVentana.setJlabel(nombre);
            nuevaVentana.modelList(nombre);
            nuevaVentana.setVisible(true);
            JframeInicio.this.dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JframeInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonSelectActionPerformed

    /**
     * @param args the command line arguments
     */
  
   

    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                try {
                    new JframeInicio().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(JframeInicio.class.getName()).log(Level.SEVERE, null, ex);
                }
               
                  
            }
        });
        
       
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JButton jButtonImportar;
    private javax.swing.JButton jButtonSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JList<String> jListContactos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
