/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import agenda.Agenda;
import agenda.Contacto;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author kanutto
 */
public class JframeContacto extends javax.swing.JFrame {

    /**
     * Creates new form JframeInicio
     */
    DefaultListModel<String> model = new DefaultListModel<>(); 
    private Contacto conct=new Contacto();
    private Agenda agen;
    private String ruta;
    
   public DefaultListModel modelList() throws FileNotFoundException {
   
     
        for(Integer tel:conct.getTelefono())
         model.addElement(Integer.toString(tel));
    
        return model;
    }
   public JframeContacto() throws FileNotFoundException{
        initComponents();
        this.setVisible(true);
        this.setExtendedState(6); 
       
        
   }
    
    public JframeContacto(Contacto co,String ruta) throws FileNotFoundException {
       
        this.agen = new Agenda(ruta);
        initComponents();
        this.ruta=ruta;
        conct=co;
        this.setVisible(true);
        this.setExtendedState(6);
        jLabelNombre.setText(conct.getNombre());
        jListTelefonos.setModel(modelList());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jScrollPanel = new javax.swing.JScrollPane();
        jListTelefonos = new javax.swing.JList<>();
        jButtonEditar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 350, 30));

        jListTelefonos.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jScrollPanel.setViewportView(jListTelefonos);

        getContentPane().add(jScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 350, 140));

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 290, 110, -1));

        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEliminar.setText("<html> <p align=\"center\">Eliminar</p> <p align=\"center\">Tlf</p> <html> ");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, -1, -1));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancelar.setText("Volver");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 110, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/62863877-red-white-wallpapers.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
     int n = JOptionPane.showConfirmDialog( null,"¿Estás seguro que desea eliminar?" ,"Eliminar Telefono", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
     if(n==JOptionPane.YES_OPTION){
        int i = jListTelefonos.getSelectedIndex();
        model.remove(i);

        agen.eliminarTelefono(conct.getNombre(), conct.getTelefono().get(i));
        conct.getTelefono().remove(i);
           try {
               agen.guardarDatos();
           } catch (IOException ex) {
               Logger.getLogger(JframeContacto.class.getName()).log(Level.SEVERE, null, ex);
           }
           
     }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        
        try {
            JframeInicio volver=new JframeInicio();
            volver.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JframeContacto.class.getName()).log(Level.SEVERE, null, ex);
        }
        JframeContacto.this.dispose();
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
       
         try {
            JframeEditar editar=new JframeEditar(conct,ruta);
            editar.setVisible(true);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JframeContacto.class.getName()).log(Level.SEVERE, null, ex);
        }
        JframeContacto.this.dispose();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
  
   

    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            
                try {
                    new JframeContacto().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(JframeContacto.class.getName()).log(Level.SEVERE, null, ex);
                }
               
               
                  
            }
        });
        
       
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JList<String> jListTelefonos;
    private javax.swing.JScrollPane jScrollPanel;
    // End of variables declaration//GEN-END:variables
}
